apiVersion: docker-machine.klusters.dev/v1alpha1
kind: Machine
metadata:
  labels:
    app.kubernetes.io/name: machine
    app.kubernetes.io/instance: machine-sample
    app.kubernetes.io/part-of: docker-machine-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: docker-machine-operator
  name: machine-sample
spec:
  # TODO(user): Add fields here
