apiVersion: v1
kind: Secret
metadata:
  name: aws-cred
  namespace: demo
type: Opaque
stringData:
  "amazonec2-access-key": "AKIAWSYRJ2YDXU7FK4CF"
  "amazonec2-secret-key": "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"